# **Flow Comtrol**

In [1]:
if True:
    print("True is true")

True is true


In [2]:
if False:
    print("False is true")

In [4]:
if 4 == 4:
    print("Hello")

Hello


In [5]:
import numpy as np

In [21]:
randum = np.random.randn()

print(f"randum {randum}")
if randum>0:
    print(randum)
    x = 3
    print(x)

print("Here")

randum 0.16165436205432743
0.16165436205432743
3
Here


In [23]:
r = np.random.randn()

if  r>0:
    print(str(r) + 'is positive')
else:
    print(str(r) + 'is negative')

1.5355373133433927is positive


In [26]:
caketype = "carrot"
caketype = "chocolate"
caketype = "dcvsdjhc"

if caketype == "carrot":
    print("Total yumminess!")
elif caketype == "chocolate":
    print("Still quite good.")
elif caketype == "fruit":
    print("Healthy?")
else:
    print("cake type not recognized.")

cake type not recognized.


In [32]:
caketype = 'Carrot'

if caketype[0].lower() == 'c': print("Probably carrot cake")


print("Probably carrot cake") if caketype[0] == "c" else print("Or not")

Probably carrot cake
Or not


In [38]:
if  10 < 3 or 4 == 4:
    print("at least one statement is true")


at least one statement is true


In [48]:
def dotproduct(a,b):
    ## Check that both vextors are numpy arrays
    if  not (isinstance(a, np.ndarray) and isinstance(b, np.ndarray)):
        raise Exception("Must be numpy array")

    ## check yhat both vectors have the same lebgth
    if not (len(a) == len(b)):
        raise Exception("Must be same length")

    ## return the dot product
    return sum(a * b)

In [49]:
a = np.array([3,4,2])
b = np.array([3,4,1])

In [50]:
dotproduct(a, b)

np.int64(27)

In [51]:
np.dot(a,b)

np.int64(27)

In [1]:
for i in range(7):
    print(i)

0
1
2
3
4
5
6


In [3]:
for j in range(4, 10):
    print(j, j**2)

4 16
5 25
6 36
7 49
8 64
9 81


In [8]:
import numpy as np

numbers = np.linspace(3, 17, 22)

for i in range(len(numbers)):
    x = numbers[i]

    print('Interation ' + str(i+1) + ' has a numbers value of ' + str(x))

Interation 1 has a numbers value of 3.0
Interation 2 has a numbers value of 3.6666666666666665
Interation 3 has a numbers value of 4.333333333333333
Interation 4 has a numbers value of 5.0
Interation 5 has a numbers value of 5.666666666666666
Interation 6 has a numbers value of 6.333333333333333
Interation 7 has a numbers value of 7.0
Interation 8 has a numbers value of 7.666666666666666
Interation 9 has a numbers value of 8.333333333333332
Interation 10 has a numbers value of 9.0
Interation 11 has a numbers value of 9.666666666666666
Interation 12 has a numbers value of 10.333333333333332
Interation 13 has a numbers value of 11.0
Interation 14 has a numbers value of 11.666666666666666
Interation 15 has a numbers value of 12.333333333333332
Interation 16 has a numbers value of 13.0
Interation 17 has a numbers value of 13.666666666666666
Interation 18 has a numbers value of 14.333333333333332
Interation 19 has a numbers value of 15.0
Interation 20 has a numbers value of 15.6666666666666

In [9]:
## soft-- coding vs hard coding

## 100s of lines of code....

for i in range(100):
    pass

In [14]:
## Modulus (reminder after division)

# 6%2 , 6/2, 7%2, 

for n in range(18):
    if n%2==0:
        print(str(n) + ' is even number')
    else:
        print(str(n) + ' is odd number')

0 is even number
1 is odd number
2 is even number
3 is odd number
4 is even number
5 is odd number
6 is even number
7 is odd number
8 is even number
9 is odd number
10 is even number
11 is odd number
12 is even number
13 is odd number
14 is even number
15 is odd number
16 is even number
17 is odd number


In [16]:
def fibonacci(n):
    list = [0, 1, 1]
    for i in range(n):
        list.append(sum(list[-2:]))

    return list

In [17]:
fibonacci(4)

[0, 1, 1, 2, 3, 5, 8]

In [22]:
list [1,2,3,4,5,6,7]

list[1, 2, 3, 4, 5, 6, 7]

In [33]:
for i in range(10):
    if i%2 == 0:
        continue  ## skipping the values
    print(i)

1
3
5
7
9


In [37]:
text = "HellO, my name is DhaVaL"

for i in text:
    if i.lower() in 'aeiou':
        continue
    print(i)

H
l
l
,
 
m
y
 
n
m
 
s
 
D
h
V
L


## While loop


``` Python

While "Condition":
    code goes here its run until condition is True

```

In [38]:
toggle = True
i = 0

while toggle:
    
    print(i)
    i += 1

    if i==8:
        toggle = False

0
1
2
3
4
5
6
7


In [ ]:
toggle = True
i = 0

while toggle:
    
    print(i)
    if i==8:
        i += 1   ## infinet loop
        toggle = False

In [40]:
i = 0

while True:
    print(i)
    i += 1
    if i == 8:
        break

0
1
2
3
4
5
6
7


In [41]:
i = 0 

while i < 8:
    print(i)
    i += 1

0
1
2
3
4
5
6
7


## for--loop: prefer when you know in advance the number of interations
## While--loop: prefer when you don't know in advance the number of interations

In [42]:
def poissonCounter(lam):

    ## initialize some variables
    counter, curvall = 0, 1

    target = np.exp(-lam)

    ## run algorithm
    while curvall > target:
        counter += 1
        curvall *= np.random.rand()

    ## return the rsult (counter) 
    return counter

In [50]:
p = np.zeros(100)

for i in range(100):
    p[i] = poissonCounter(10)
p

array([ 7.,  8., 16.,  9.,  6.,  8., 13., 12., 14., 14., 14., 15., 11.,
       10., 12., 12., 12., 10., 13., 19., 10.,  7., 13.,  7., 14.,  6.,
       10., 12., 15., 14., 11.,  5., 17., 14.,  9.,  8., 10.,  6.,  8.,
        8., 12., 12., 13., 15., 14.,  8., 10.,  9., 14., 17., 11., 13.,
        6.,  9., 17., 12.,  6., 11., 13., 10., 13., 11.,  6., 17., 12.,
       16., 10., 12., 15., 12., 10., 16.,  8., 14., 11., 11.,  7., 16.,
       11., 10.,  6.,  6., 14.,  9., 21.,  9., 19., 14.,  9., 12., 12.,
       11., 13., 11.,  8.,  9., 11.,  8., 13., 12.])

In [80]:
## same functionality but hard to read

def poissonCounter(l):
    k, p, t = 0, 1, np.exp(-l)

    while p > t:
        k += 1
        p *= np.random.rand()
        # print(p)

    return k

In [81]:
np.exp(-10)

np.float64(4.5399929762484854e-05)

In [82]:
poissonCounter(10)

8

In [84]:
## initialization

for i in range(10):
    r[i] = i **2

print(r)

NameError: name 'r' is not defined

In [106]:
n = 32

r = np.zeros(n)
for i in range(n):
    r[i] = i **2

print(r)

[  0.   1.   4.   9.  16.  25.  36.  49.  64.  81. 100. 121. 144. 169.
 196. 225. 256. 289. 324. 361. 400. 441. 484. 529. 576. 625. 676. 729.
 784. 841. 900. 961.]


In [ ]:
r = 10
n = np.zeros(r)
n = np.full(r, 12.1232434) 
n

array([12.1232434, 12.1232434, 12.1232434, 12.1232434, 12.1232434,
       12.1232434, 12.1232434, 12.1232434, 12.1232434, 12.1232434])

In [128]:
# del r

r = []
n = 20

for i in range(n):
    r.append(i**2)
r

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361]

In [132]:
r = np.array([])
n = 20

for i in range(n):
    r = np.append(r, i**2)
r

array([  0.,   1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.,
       121., 144., 169., 196., 225., 256., 289., 324., 361.])

In [137]:
r = np.zeros((4,5))
r[1,3] = 8
r

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [149]:
import time

N = 1000000

tic = time.perf_counter()
r = []

for i in range(N):
    r.append(i**2)
t = (time.perf_counter() - tic) * 1000
t

93.28554099192843

In [ ]:
N = 1000000

tic = time.perf_counter()
r = np.array([])

for i in range(N):
    r = np.append(r, i**2)
t = (time.perf_counter() - tic) * 1000
t

In [151]:
N = 1000000

tic = time.perf_counter()
r = np.zeros(N)

for i in range(N):
    r[i] = i**2
t = (time.perf_counter() - tic) * 1000
t

147.33187499223277

#### Function error checking

In [191]:
def funfun(x, y):

    # check that inputs are numeric
    if not isinstance(x, (int, float)):
        if isinstance (x, str) and x.isnumeric():
            x = float(x)
            print(type(x))
            print("Note: converted x to float")
        else:
            raise Exception("Input x must be a number")
    z = x * y

    return z
funfun(3,'hi')

'hihihi'

In [192]:
funfun('dfhjb', 5)

Exception: Input x must be a number

In [193]:
funfun("2", 5)

<class 'float'>
Note: converted x to float


10.0

In [197]:
def funfunfun(x, y):
    try:
        z = x**y
    except:
        print("Couldn't complete the mission")

    return z

In [198]:
funfunfun(3,4)

81

In [199]:
funfunfun(3,'4')

Couldn't complete the mission


UnboundLocalError: cannot access local variable 'z' where it is not associated with a value

In [212]:
somelist = [3,4,5,6]
otherlist = ['a', 'b', 'c', 'd']

for j, i in zip(somelist, otherlist):
    print(i, j)

a 3
b 4
c 5
d 6


In [213]:
z = zip(somelist, otherlist)
z

In [214]:
lz = list(z)

In [215]:
lz

[(3, 'a'), (4, 'b'), (5, 'c'), (6, 'd')]

In [216]:
dic = {"a": 1, "b":2}

In [218]:
for key in dic:
    print(key)

a
b


In [222]:
for key, val in dic.items():
    print()

In [230]:
names = ['alpha', 'beta', 'gamma']
values = [10, 20, 30]

D = dict()
for i in zip(names, values):
    D.update(zip(names, values))
D

{'alpha': 10, 'beta': 20, 'gamma': 30}

In [241]:
## Reminder 

import random

# if random.randint(1, 10) > 5 : print("This is a large number")

print("This is number is samll") if random.randint(1, 10) < 5 else print("This is number is big")

This is number is big


In [242]:
for i in range(10):
    print(i**2)

0
1
4
9
16
25
36
49
64
81


In [ ]:
[print(i**2) for i in range(10)]

0
1
4
9
16
25
36
49
64
81


[None, None, None, None, None, None, None, None, None, None]

In [247]:
n = [i**2 - i**(1/2) for i in range(10) if i > 5]
n

[33.55051025721682, 46.35424868893541, 61.17157287525381, 78.0]

In [249]:
6**2 - 6**(1/2)

33.55051025721682

In [250]:
text = ["Promising", "Yves", "that", "home", "on", "Nobb"]

for word in text:
    print(word[0])

P
Y
t
h
o
N


In [252]:
[print(word[0]) for word in text];

P
Y
t
h
o
N


In [255]:
newlist = ['']*10

# [newlist[i] = 'Odd' for i in range(10) if i%2 == 1 else newlist[i] = i ];

[ 'Odd' if i%2 == 1 else i for i in range(10)]

[0, 'Odd', 2, 'Odd', 4, 'Odd', 6, 'Odd', 8, 'Odd']

In [256]:
x1 = np.linspace(-3, 3, 11)
y1 = x1 **2
x1, y1

(array([-3. , -2.4, -1.8, -1.2, -0.6,  0. ,  0.6,  1.2,  1.8,  2.4,  3. ]),
 array([9.  , 5.76, 3.24, 1.44, 0.36, 0.  , 0.36, 1.44, 3.24, 5.76, 9.  ]))

In [266]:
x1 = [ i/(5/3) for i in range(-5, 6)]
y1 = [ i**2 for i in x1 ]

x1, y1

([-3.0,
  -2.4,
  -1.7999999999999998,
  -1.2,
  -0.6,
  0.0,
  0.6,
  1.2,
  1.7999999999999998,
  2.4,
  3.0],
 [9.0,
  5.76,
  3.2399999999999993,
  1.44,
  0.36,
  0.0,
  0.36,
  1.44,
  3.2399999999999993,
  5.76,
  9.0])

In [281]:
import copy

X = np.array([ [1,2,3],
               [2,3,4],
               [3,4,5],
               [4,5,6] ])

w = np.array([10, 20, 30])

Y = copy.deepcopy(X)
for i in range(X.shape[0]):
    Y[i, :] = Y[i, :] + w

In [282]:
Y, X

(array([[11, 22, 33],
        [12, 23, 34],
        [13, 24, 35],
        [14, 25, 36]]),
 array([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]]))

In [284]:
Y = X + w
Y

array([[11, 22, 33],
       [12, 23, 34],
       [13, 24, 35],
       [14, 25, 36]])

In [290]:
w = np.array([-1, 0, 1, 0], ndmin=2).T

X*w

array([[-1, -2, -3],
       [ 0,  0,  0],
       [ 3,  4,  5],
       [ 0,  0,  0]])

In [291]:
list = []
for i in  range(9):
    list.append(i)
list

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [293]:
v = np.arange(9)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [305]:
x = np.reshape(v, shape=(3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [306]:
C = np.tile(x, reps=(3,1))

In [304]:
np.tile(x, reps=3).T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8],
       [0, 3, 6],
       [1, 4, 7],
       [2, 5, 8],
       [0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [309]:
z = C * np.reshape(v, (len(v),1))

In [310]:
z

array([[ 0,  0,  0],
       [ 3,  4,  5],
       [12, 14, 16],
       [ 0,  3,  6],
       [12, 16, 20],
       [30, 35, 40],
       [ 0,  6, 12],
       [21, 28, 35],
       [48, 56, 64]])